FROM eclipse-temurin:21-jdk

WORKDIR /app

# Copiamos solo lo necesario para que gradle funcione
COPY gradlew ./gradlew
COPY gradle ./gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew

# Descargar dependencias (cache)
RUN ./gradlew dependencies --no-daemon || true

# Ahora copiamos SOLO el código fuente
COPY src ./src

# Compilar
RUN ./gradlew clean build -x test --no-daemon

EXPOSE 8081

CMD ["sh", "-c", "java -Dspring.profiles.active=docker -jar build/libs/*-SNAPSHOT.jar"]
