spring.neo4j.uri=${NEO_URL:bolt://localhost:7687}
spring.neo4j.authentication.username=${NEO_USER:neo4j}
spring.neo4j.authentication.password=${NEO_PASSWORD:rootroot}
logging.level.org.springframework.data.neo4j=DEBUG
spring.datasource.url=jdbc:postgresql://localhost:5432/epersgeist
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.mongodb.uri=mongodb://localhost:27017/epersgeist
spring.data.mongodb.database=epersgeist
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=60000