# Postgres Railway
server.port=8080
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.show-sql=false
spring.jpa.generate-ddl=false
# Redis Railway
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0
spring.data.redis.timeout=60000
# Neo4J Aura
spring.neo4j.uri=${NEO_URI}
spring.neo4j.authentication.username=${NEO_USER}
spring.neo4j.authentication.password=${NEO_PASSWORD}
# MongoDB Atlas
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}
# logging.level.org.springframework=INFO
